peoplehuntr/config/routes.rb
Peoplehuntr::Application.routes.draw do  resources :listings  
  root :to => 'listings#new'

  resources :users

  resources :groups

end

peoplehuntr/app/models/group.rb
class Group < ActiveRecord::Base
end

peoplehuntr/app/models/user.rb
class User < ActiveRecord::Base
	#rails g scaffold User first_name:string last_name:string name:string registered_user:boolean bio:string skill_string:string need_string:string linkedin_token:string github_token:string linkedin_username:string github_username:string linkedin_data_api:string github_data_api:string photo:string 
	attr_accessible :first_name, :last_name, :name, :registered_user, :bio, :skill_string, :need_string, :linkedin_token, :github_token, :linkedin_username, :github_username, :linkedin_data_api, :github_data_api, :photo
end

peoplehuntr/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

peoplehuntr/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:nickname, :name, :location, :event_time, :status, :is_complete)
    end
end

peoplehuntr/app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @groups = Group.all
  end 

  def new
       @user = User.new
  end 


  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :name, :bio, :registered_user, :skill_string, :need_string, :linkedin_token, :github_token, :linkedin_username, :github_username, :linkedin_data_api, :github_data_api, :photo)
    end
end

peoplehuntr/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :name, :registered_user, :bio, :skill_string, :need_string, :linkedin_token, :github_token, :linkedin_username, :github_username, :linkedin_data_api, :github_data_api, :photo)
    end
end

peoplehuntr/app/helpers/application_helper.rb
module ApplicationHelper
end

peoplehuntr/app/helpers/groups_helper.rb
module GroupsHelper
end

peoplehuntr/app/helpers/users_helper.rb
module UsersHelper
end

peoplehuntr/app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nickname %><br>
    <%= f.text_field :nickname %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :event_time %><br>
    <%= f.datetime_select :event_time %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :is_complete %><br>
    <%= f.check_box :is_complete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

peoplehuntr/app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

peoplehuntr/app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <thead>
    <tr>
      <th>Nickname</th>
      <th>Name</th>
      <th>Location</th>
      <th>Event time</th>
      <th>Status</th>
      <th>Is complete</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.nickname %></td>
        <td><%= group.name %></td>
        <td><%= group.location %></td>
        <td><%= group.event_time %></td>
        <td><%= group.status %></td>
        <td><%= group.is_complete %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

peoplehuntr/app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

peoplehuntr/app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nickname:</strong>
  <%= @group.nickname %>
</p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @group.location %>
</p>

<p>
  <strong>Event time:</strong>
  <%= @group.event_time %>
</p>

<p>
  <strong>Status:</strong>
  <%= @group.status %>
</p>

<p>
  <strong>Is complete:</strong>
  <%= @group.is_complete %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

peoplehuntr/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta name="description" content="Neon Admin Panel" />
	<meta name="author" content="" />
	
	<title>PeopleHunt.us | Meet people intelligently. </title>
	 <link data-turbolinks-track="true" href="<%= asset_path '/assets/phstyle.css' %>" media="all" rel="stylesheet" />
	


  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
	<!--[if lt IE 9]><script src="/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->
	
	
</head>
<body class="page-body" >

<div class="page-container horizontal-menu">
<header class="navbar navbar-fixed-top"><!-- set fixed position by adding class "navbar-fixed-top" -->
		
		<div class="navbar-inner">
		
			<!-- logo -->
			<div class="navbar-brand">
				<a href="/" height="50px">
					<img src="<%= asset_path '/assets/images/PeopleHunt.png' %>"  alt="" width="65px" style="margin-bottom: -10px" />
				</a>
			</div>
			
			
			<!-- main menu -->
						
			<ul class="navbar-nav">
				<li class="opened ">
					<a href="/users/new">
						<i class="glyphicon-plus"></i>
						<span>Search a New Event</span>
					</a>
				</li>	
				<li class="opened ">
					<a href="/groups/">
						<i class="entypo-location"></i>
						<span>My Events</span>
					</a>
					<ul>
						
						<li>
							<a href="skin-black.html">
								<span>Locations</span>
							</a>
							<ul>
								<li>
									<a href="/">
										<span>San Francisco</span>
									</a>
								</li>
								<li>
									<a href="/">
										<span>Chicago</span>
									</a>
								</li>
							</ul>
						</li>
						
					
					</ul>
				</li>
				
			
				<!-- Search Bar -->
				<li id="search" class="search-input-collapsed">
					<!-- add class "search-input-collapsed" to auto collapse search input -->
					<form method="get" action="">
						<input type="text" name="q" class="search-input" placeholder="Search something..."/>
						<button type="submit">
							<i class="entypo-search"></i>
						</button>
					</form>
				</li>
			</ul>
						
			
			<!-- notifications and other links -->
			<ul class="nav navbar-right pull-right">
				
				
				
				<li class="dropdown">
					
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
						<i class="entypo-mail"></i>
						<span class="badge badge-secondary">10</span>
					</a>
					
					<!-- dropdown menu (messages) -->
					<ul class="dropdown-menu">
					

					</ul>
					
				</li>
				
				<!-- raw links -->
				
								
				<li class="sep"></li>
				
				<li>
					<a href="extra-login.html">
						Log Out <i class="entypo-logout right"></i>
					</a>
				</li>
				
				
				<!-- mobile only -->
				<li class="visible-xs">	
				
					<!-- open/close menu icon (do not remove if you want to enable menu on mobile devices) -->
					<div class="horizontal-mobile-menu visible-xs">
						<a href="#" class="with-animation"><!-- add class "with-animation" to support animation -->
							<i class="entypo-menu"></i>
						</a>
					</div>
					
				</li>
				
			</ul>
	
		</div>
		
	</header>	

<img src="" width="100%" height= "280px" style="font-size: 28px; background: url('/assets/hackathon.jpg') no-repeat center left ;background-position-x: 0%; background-position-y: 50%; background-size: cover; background-repeat-x: no-repeat; background-repeat-y: no-repeat;background-attachment: initial; background-origin: initial; background-clip: initial; background-color: initial; opacity: 0.7;
    filter: alpha(opacity=70); /* For IE8 and earlier */">
<div class="maintitle" style="color: #fff; font-size: 30px; font-weight: 900;  text-shadow: 2px 2px 4px #000000; background-color: rgba(0,0,0,.6); padding: 8px 50px 8px 60px; position: absolute; top: 100px; left: 0px; ">
	Meet people intelligently
</div>
<div class="mainsubtitle" style="color: #fff; font-size: 22px; font-weight: 300; background-color: rgba(0,0,0,.7); padding: 5px 50px 5px 60px; position: absolute; top: 200px; left: 0px; ">
	Connect with the people who share your interests at every event. 
</div>



	<div class="main-content">
		
				<div class="container">
			<div class="row">
				<div class="col-md-12">


<%= yield %>





</div>
</div>
</div>

<footer class="main">
	
			
	&copy; 2014 <strong>PeopleHunt.us</strong> Meet people intelligently. <br>
	Don't waste a second. Connect with the people you will want to get to know at every event. 

	
</footer>	

</div> <!-- end main-content -->


</div>
	
	

<% if Rails.env.production? %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-143082-18', 'auto');
  ga('send', 'pageview');

</script>
<% end %>



</body>
</html>

peoplehuntr/app/views/listings/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_field :bio %>
  </div>
  <div class="field">
    <%= f.label :registered_user %><br>
    <%= f.check_box :registered_user %>
  </div>
  <div class="field">
    <%= f.label :skill_string %><br>
    <%= f.text_field :skill_string %>
  </div>
  <div class="field">
    <%= f.label :need_string %><br>
    <%= f.text_field :need_string %>
  </div>
  <div class="field">
    <%= f.label :linkedin_token %><br>
    <%= f.text_field :linkedin_token %>
  </div>
  <div class="field">
    <%= f.label :github_token %><br>
    <%= f.text_field :github_token %>
  </div>
  <div class="field">
    <%= f.label :linkedin_username %><br>
    <%= f.text_field :linkedin_username %>
  </div>
  <div class="field">
    <%= f.label :github_username %><br>
    <%= f.text_field :github_username %>
  </div>
  <div class="field">
    <%= f.label :linkedin_data_api %><br>
    <%= f.text_field :linkedin_data_api %>
  </div>
  <div class="field">
    <%= f.label :github_data_api %><br>
    <%= f.text_field :github_data_api %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

peoplehuntr/app/views/listings/index.html.erb
<h1>Listing users</h1>

<table>
 

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.name %></td>
        <td><%= user.bio %></td>
        <td><%= user.registered_user %></td>
        <td><%= user.skill_string %></td>
        <td><%= user.need_string %></td>
        <td><%= user.linkedin_username %></td>
        <td><%= user.github_username %></td>
        <td><%= user.photo %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

peoplehuntr/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :registered_user %><br>
    <%= f.check_box :registered_user %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_field :bio %>
  </div>
  <div class="field">
    <%= f.label :skill_string %><br>
    <%= f.text_field :skill_string %>
  </div>
  <div class="field">
    <%= f.label :need_string %><br>
    <%= f.text_field :need_string %>
  </div>
  <div class="field">
    <%= f.label :linkedin_token %><br>
    <%= f.text_field :linkedin_token %>
  </div>
  <div class="field">
    <%= f.label :github_token %><br>
    <%= f.text_field :github_token %>
  </div>
  <div class="field">
    <%= f.label :linkedin_username %><br>
    <%= f.text_field :linkedin_username %>
  </div>
  <div class="field">
    <%= f.label :github_username %><br>
    <%= f.text_field :github_username %>
  </div>
  <div class="field">
    <%= f.label :linkedin_data_api %><br>
    <%= f.text_field :linkedin_data_api %>
  </div>
  <div class="field">
    <%= f.label :github_data_api %><br>
    <%= f.text_field :github_data_api %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

peoplehuntr/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

peoplehuntr/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Name</th>
      <th>Registered user</th>
      <th>Bio</th>
      <th>Skill string</th>
      <th>Need string</th>
      <th>Linkedin token</th>
      <th>Github token</th>
      <th>Linkedin username</th>
      <th>Github username</th>
      <th>Linkedin data api</th>
      <th>Github data api</th>
      <th>Photo</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.name %></td>
        <td><%= user.registered_user %></td>
        <td><%= user.bio %></td>
        <td><%= user.skill_string %></td>
        <td><%= user.need_string %></td>
        <td><%= user.linkedin_token %></td>
        <td><%= user.github_token %></td>
        <td><%= user.linkedin_username %></td>
        <td><%= user.github_username %></td>
        <td><%= user.linkedin_data_api %></td>
        <td><%= user.github_data_api %></td>
        <td><%= user.photo %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

peoplehuntr/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

peoplehuntr/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Registered user:</strong>
  <%= @user.registered_user %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<p>
  <strong>Skill string:</strong>
  <%= @user.skill_string %>
</p>

<p>
  <strong>Need string:</strong>
  <%= @user.need_string %>
</p>

<p>
  <strong>Linkedin token:</strong>
  <%= @user.linkedin_token %>
</p>

<p>
  <strong>Github token:</strong>
  <%= @user.github_token %>
</p>

<p>
  <strong>Linkedin username:</strong>
  <%= @user.linkedin_username %>
</p>

<p>
  <strong>Github username:</strong>
  <%= @user.github_username %>
</p>

<p>
  <strong>Linkedin data api:</strong>
  <%= @user.linkedin_data_api %>
</p>

<p>
  <strong>Github data api:</strong>
  <%= @user.github_data_api %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @user.photo %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>